"""softdeletes

Revision ID: 5703d0209eba
Revises: f51216ed6c1f
Create Date: 2025-10-22 22:23:44.539454

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '5703d0209eba'
down_revision = 'f51216ed6c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('item', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('item_type', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('rental_session', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('strike', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strike', 'is_deleted')
    op.drop_column('rental_session', 'is_deleted')
    op.drop_column('item_type', 'is_deleted')
    op.drop_column('item', 'is_deleted')
    op.drop_column('event', 'is_deleted')
    # ### end Alembic commands ###
