"""add_item_type_id_to_rental_session

Revision ID: cd6d6c2a22ee
Revises: 498e4ee72e00
Create Date: 2025-08-11 15:29:12.315690

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'cd6d6c2a22ee'
down_revision = '498e4ee72e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_session', sa.Column('item_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rental_session', 'item_type', ['item_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental_session', type_='foreignkey')
    op.drop_column('rental_session', 'item_type_id')
    # ### end Alembic commands ###
