"""add fullname

Revision ID: f51216ed6c1f
Revises: fb8a57b65c4d
Create Date: 2025-10-07 13:04:18.238966

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f51216ed6c1f'
down_revision = 'fb8a57b65c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_session', sa.Column('user_fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_session', 'user_fullname')
    # ### end Alembic commands ###
