"""deadline_ts_rental_session

Revision ID: fb8a57b65c4d
Revises: fccbec47bef3
Create Date: 2025-09-25 19:40:23.737319

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8a57b65c4d'
down_revision = 'fccbec47bef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental_session', sa.Column('deadline_ts', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental_session', 'deadline_ts')
    # ### end Alembic commands ###
